### ISSUE TITLE
Return values ...

### ISSUE THREAD

**Issue by Brixxyke** [sowdust/searchbook#10]
The script is still working, but I have an issue, maybe just me ? The return values for a stories connected search like stories-liked or stories commented for a specific time interval as a result returns all kind of results but not only in the specified time range, and I think it returns also less results for the related search ... It's only me who's facing this issue or working this way for everyone ?

**Comment by manodemona** [comment]
I have the same problem. Red bar doesn't show.

**Comment by Zutalorz** [comment]
i dont have any issues using the extension.  long may  it last ;) 

btw.  what you see when you get the search results is up to facebook not the extension, the extension simply allows you to view your results.

**Comment by sowdust** [comment]
please provide an example query

**Comment by Brixxyke** [comment]
As you can see on the picture there's all kind of returns from all kind of time ranges 
![kép](https://user-images.githubusercontent.com/52039257/61201175-08172680-a6e4-11e9-9802-d98d027e36af.png)

It was a simple example of my profile search for stories-liked(1321683060) , but still returns a lot of other time range results, and here is the address query: https://www.facebook.com/search/top/?q=nagy%20levente&epa=FILTERS&filters=eyJycF9jcmVhdGlvbl90aW1lIjoie1wibmFtZVwiOlwiY3JlYXRpb25fdGltZVwiLFwiYXJnc1wiOlwie1xcXCJzdGFydF9tb250aFxcXCI6XFxcIjIwMTktMDdcXFwiLFxcXCJlbmRfbW9udGhcXFwiOlxcXCIyMDE5LTA3XFxcIn1cIn0ifQ%3D%3D

**Comment by sowdust** [comment]
You cannot mix Facebook regular search and graph-like searches. If you use the extension, the query executed is the one you wrote and overwrites all other parameters set in any other way (ie thru Facebook search side box). In your query, "stories-liked(1321683060)", there is no indication about the time interval you want to search for, therefore results are from any date. Please read the README

**Comment by daniellx591** [comment]
Hello, when i "Set" values on the extension, it doesnot returns any result, can you tell me what i am doing wrong?

![set](https://user-images.githubusercontent.com/52880664/61207197-63e5ad80-a6ec-11e9-84cf-248598b909a1.PNG)

**Comment by sowdust** [comment]
please do not post your personal issues everywhere.

**Comment by daniellx591** [comment]
Hello,

I am trying now to use your extension and gives an error message, like this:

Can you please check this and help me?

regards

Daniel

Mattia <notifications@github.com> escreveu no dia segunda, 15/07/2019 à(s)
15:58:

**Comment by sowdust** [comment]
what about "please do not post your personal issues everywhere." is not clear?

**Comment by daniellx591** [comment]
Mattia, i will delete my post with my printscreen, thank you my friend.

Mattia <notifications@github.com> escreveu no dia segunda, 15/07/2019 à(s)
17:02:

**Comment by daniellx591** [comment]
Good morning my friend,

So i saw that the extension is not working anymore, so is there another way?

Regards

Zhms <zhms.sales@gmail.com> escreveu no dia segunda, 15/07/2019 à(s) 17:09:
