### ISSUE TITLE
Could the new graphsearch workaround for a users tagged-photos be implemented into Ultimate-Facebook-Scraper which uses selenium & webDriver?

### ISSUE THREAD

**Issue by github-userx** [sowdust/searchbook#11]
https://github.com/harismuneer/Ultimate-Facebook-Scraper

Before Facebooks GraphSearch changes we could retrieve the tagged photos of a user *that we are not friends with on Facebook* easily just through the Graph URL facebook.com/search/userID/photos-tagged

Unfortunately this isn’t possible anymore with the new graph search changes/restrictions.

Mattia, do You think Your new graphsearch workaround with (intersect)( could somehow be implemented into the fantastic piece of software that Ultimate-Facebook-Scraper is?

Have You generally already taken a look at UFS‘ capabilities and functionalities?

(Disclaimer: I’m not a programmer myself)

**Comment by sowdust** [comment]
I have not tried UFS yet, but it should be possible to implement the method I am using into the scraper, since it uses a browser session
