### ISSUE TITLE
no results

### ISSUE THREAD

**Issue by ghost** [sowdust/searchbook#15]

**Comment by fabykika** [comment]
mine doesn't work either

**Comment by zchryy03** [comment]
Let's wait again for @sowdust

**Comment by walli44** [comment]
Last evening I used it for the first time (chrome) and it worked well. This morning it doesn't work anymore.

**Comment by fabykika** [comment]
I use it in firefox and it doesn't work anymore

**Comment by zchryy03** [comment]
Guys, patience. I'm sure sowdust is doing something for this right now. I hope he'll be able to fix this. If not, then still a huge thanks to him for this tool that we've used to our advantage.

**Comment by lukas-derksen** [comment]
I'm not so sure about that... He just posted an update on his facebook search page, saying it stopped working: https://sowdust.github.io/fb-search/

**Comment by sowdust** [comment]
sorry but Facebook has closed this particular search endpoint. We'll see if we can find another one ... after the holidays. You can still use https://sowdust.github.io/fb-search/ which is a better interface for Facebook search box.

**Comment by zchryy03** [comment]
@sowdust we'll wait. Thank you

**Comment by ddobrev** [comment]
Hello @sowdust . Assuming you meant the summer holidays, may I hope I'm going to see more of your brilliant work soon?

**Comment by sowdust** [comment]
Thanks @ddobrev . These days I am busy on other topics. If I will develop something of this kind, you will find it among my repo's ;)
