### ISSUE TITLE
Could you make a version for Chromium too ? 

### ISSUE THREAD

**Issue by mikhoul** [sowdust/searchbook#2]
Could you make a version for Chromium too ?  🤔

They almost use the same API's  and many Chromium forks (like Brave, Kiwi etc) stated officially will keep the webRequest  API as it is so your work will not be done in vain.

Thanks for your work ! 👍  :octocat:

**Comment by mikhoul** [comment]
Opps just to let you know that with [Kiwi Browser](https://play.google.com/store/apps/details?id=com.kiwibrowser.browser&hl=fr_CA) on Android you can use the webRequest API (and 99% of the Chrome extensions) so a Chromium version of your extension would work on Android too.

Kiwi is very fast and is privacy oriented and for power-users, you can participate or just follow the development here: https://discordapp.com/channels/494814211579445270/494814211579445274  Nightly builds are also available on the channel.

Arnaud Granal is the développer.

:octocat: Regards

**Comment by github-userx** [comment]
Lol KiwiBrowser is privacy oriented but uses discord..?

**Comment by mikhoul** [comment]
[**@github-userx**](https://github.com/github-userx) commented on [17 juin 2019 à 14:05 UTC−4](https://github.com/sowdust/searchbook/issues/2#issuecomment-502790536 "2019-06-17T18:05:48Z - Replied by Github Reply Comments"):
> Lol KiwiBrowser is privacy oriented but uses discord..?

What is your problem with discord  ?   what is your argument against the fact that Kiwi is privacy oriented ?

Discord it's an excellent tool to collaborate and growing  community around projects. Unless you use your real name in Discord there is no privacy issue.

Moreover you bring nothing constructive to this issue about porting the extension to Chromium except making empty claims that have nothing to do with the issue. you should go away.

**Comment by sowdust** [comment]
I could, but I was waiting to test the extension a little bit, fix some bugs, maybe receive some feedback from users and see if Fb kills this search possibility or not. If things get stable I will try to port this to a Chrome extension too

**Comment by github-userx** [comment]
https://stallman.org/discord.html

It’s absolutely fine if you choose to use discord. I am neither judging you or discord itself. I am just stating that they are a company and software/service that does not respect privacy at all and logs and stores everything forever and are not opensource or privacy oriented at all.

I apologize for coming into this thread. I saw it in my email inbox because I was „watching“ this repository.

**Comment by mikhoul** [comment]
[**@sowdust**](https://github.com/sowdust) commented on [17 juin 2019 à 17:06 UTC−4](https://github.com/sowdust/searchbook/issues/2#issuecomment-502850950 "2019-06-17T21:06:09Z - Replied by Github Reply Comments"):
> I could, but I was waiting to test the extension a little bit, fix some bugs, maybe receive some feedback from users and see if Fb kills this search possibility or not. If things get stable I will try to port this to a Chrome extension too

My guess is that now the graph search is no longer user friendly they will keep it this way, especially since it require to use it knowledge that average users don't have and that they are not willing to learn.

IMO FB restrained the "Graph search" in face of the privacy issues FB is facing around the world by various government body.

If you do a quick dirty port for Chrome I will test it and report to you if I see bugs. I did not look at the code but in the past I used a polyfill to adapt some extensions I used in Firefox but I'm not really a JS programmer but it could be useful for you to port your extension with minimal effort: https://github.com/mozilla/webextension-polyfill and https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Build_a_cross_browser_extension

Best Regards :octocat:

**Comment by mikhoul** [comment]
Here's a list of various polyfill that could help you to make it more easy to port your extension to Chromium:

https://github.com/tfoxy/chrome-promise
https://github.com/acvetkov/then-chrome
https://github.com/KeithHenry/chromeExtensionAsync

Regards :octocat:

**Comment by sowdust** [comment]
I am sorry, but since I am doing this in my free time, which is very little, I cannot afford maintaining two versions of the same extension before they are at least close to being stable. First I will correct bugs and eventually add features on the one that is in development. If, meanwhile, you want to port the extension while it is in development, feel free to make a pull request

**Comment by sowdust** [comment]
I have not forgotten about this. As you might have seen from today's changes, things are far from stable though...

**Comment by sowdust** [comment]
Here you go https://github.com/sowdust/searchbook-chrome
