### ISSUE TITLE
Coding FB Search

### ISSUE THREAD

**Issue by jmerenee** [sowdust/searchbook#3]
Apologies in advance for being somewhat clueless in my quest. I have a url saved that seems to have been created by you. I've also tried the README and not schooled enough in coding to get it to work. Any chance you can help me? I'm happy to donate for your time. Thanks.

**Comment by sowdust** [comment]
Please do not ask the same thing several times in different channels.

**Comment by jmerenee** [comment]
So sorry! I just don't know how to directly communicate like I was hoping to! Thanks.
