### ISSUE TITLE
Extension now shows results in mobile layout?

### ISSUE THREAD

**Issue by Delariu** [sowdust/searchbook#4]
Hi, I was just wondering if the extension started outputting results in the mobile layout for anyone else (it does for me since about an hour ago)? and if so, whether that might be a sign Facebook has begun to plug this particular loophole too.

I was hoping you had a better idea of what was going on at your end. Could just be a bug only I am faced with, but it's pretty persistent. Wouldn't be surprised if Facebook caught on to this functionality still being accessible though.

**Comment by github-userx** [comment]
Honestly, I actually have started to think that all these new fb tools should be made private immediately so fb doesn’t catch up with it all the time and closes these loopholes.

**Comment by sowdust** [comment]
Still working for me. github-userx good to know your opinion, but if it wasn't for people publishing these tools for free you either had to develop your own or pay a lot of money to get access.

**Comment by github-userx** [comment]
Very true Mattia!

**Comment by mikhoul** [comment]
[**@sowdust**](https://github.com/sowdust) commented on [25 juin 2019 à 05:36 UTC−4](https://github.com/sowdust/searchbook/issues/4#issuecomment-505367679 "2019-06-25T09:36:53Z - Replied by Github Reply Comments"):
> if it wasn't for people publishing these tools for free you either had to develop your own or pay a lot of money to get access.

Knowledge must be shared freely not hidden or restricted to a small group of insider or to people who have money to buy it, that's how knowledge grow.

Regards :octocat:
