### ISSUE TITLE
Find common friends 

### ISSUE THREAD

**Issue by juanmgar** [sowdust/searchbook#5]
You could also find friends in common using the intersection with 'friends' operator, for example: intersect(friends(facebookIdA),friends(facebookIdB))

**Comment by massimosclaw** [comment]
@juanmgar  Do you know how this could be extended to friends of friends, not just mutual friends?

**Comment by sowdust** [comment]
I don't know if it can be helpful, but you could try using my other tool, ffff: https://github.com/sowdust/ffff, so find someone's friends
