### ISSUE TITLE
Intersect Queries

### ISSUE THREAD

**Issue by Gallahad87** [sowdust/searchbook#6]
The majority of my attempts at combining queries using intersect aren't working. 

For example: _intersect(pages-liked(4),pages-named(Zuckerberg))_ should be returning results but doesn't.

Each query on its own brings results but combining them together using intersect bring back nul. Does anyone know if I need to be writing the query a different way? Or is it just a case that intersect is not functional for these sorts of searches?

**Comment by 54lv4** [comment]
mmm nope, happens the same on this end...

**Comment by sowdust** [comment]
Even before FB closed the Graph Search they disabled many "intersect" queries. I am afraid there isn't much to do about it : (
