### ISSUE TITLE
Extension no longer working

### ISSUE THREAD

**Issue by rquinn852** [sowdust/searchbook#7]
I've used Searchbook regularly since it's release, but it no longer seems to be working.

The red intercept bar is no longer appearing on my screen and the results of my query are not shown.

**Comment by Zutalorz** [comment]
same here

**Comment by 4abetterworld** [comment]
I agree it's not working anymore. Same problem for me.

**Comment by fabykika** [comment]
it no longer works

**Comment by ghost** [comment]
same issue

**Comment by hhughes03** [comment]
I had been using it too. It has stopped working.

**Comment by zchryy03** [comment]
let's wait for @sowdust

**Comment by 54lv4** [comment]
The same here. Hope @sowdust can work it out

**Comment by fabykika** [comment]
help @sowdust

**Comment by sowdust** [comment]
Facebook has made changes which prevented the extension from working. I have updated the extension with a simple workaround. I don't think it will last long, but as of now it works.

**Comment by manodemona** [comment]
Last update didn't work for me. The red bar still doesn't show.
