### ISSUE TITLE
Extension stopped working

### ISSUE THREAD

**Issue by Delariu** [sowdust/searchbook#8]
The extension stopped working. The interface no longer pops up, so it doesn't even convert the queries anymore. Not sure what happened since it died on a refresh but a redownload and a new install didn't fix anything. Has anyone else experienced this?

**Comment by rquinn852** [comment]
Ditto: https://github.com/sowdust/searchbook/issues/7

**Comment by Delariu** [comment]
Gonna close this one because it's identical to an earlier opened issue. Sorry I didn't notice sooner.

**Comment by 4abetterworld** [comment]
yes i have the same problem...
