### ISSUE TITLE
extention for firfox no longer opens

### ISSUE THREAD

**Issue by duceman2000** [sowdust/searchbook#9]
I have downloaded the new version & added the mainfest.json file as a temporary extention. when i go to facebook the extention doesnt show up.

**Comment by 54lv4** [comment]
I just tested it, is working on this end

**Comment by ghost** [comment]
hmmm,  same,  just checked and no issue on my end either.

**Comment by duceman2000** [comment]
i just fixed it. was not allowed in private mode
